### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: axis 0 specified more than once.

### ISSUE THREAD

**Issue by cwzat** [rohitgirdhar/ActionVLAD#8]
I run your demo, and I get the error in eval_image_classifier.py
`INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.InvalidArgumentError'>, axis 0 specified more than once.
	 [[Node: ReverseV2 = ReverseV2[T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](stack, ReverseV2/axis)]]
Traceback (most recent call last):
  File "eval_image_classifier.py", line 360, in <module>
    tf.app.run()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "eval_image_classifier.py", line 340, in main
    res[epname].append(feats[eid])
  File "/anaconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 964, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1235, in _single_operation_run
    target_list_as_strings, status, None)
  File "/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: axis 0 specified more than once.
	 [[Node: ReverseV2 = ReverseV2[T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](stack, ReverseV2/axis)]]`
How can I solve it ?

**Comment by rohitgirdhar** [comment]
What TF version are you using? If you're using a newer version (>= v1.0), you might need to change the code to be compatible with it. Specifically there's a [`tf.reverse` here](https://github.com/rohitgirdhar/ActionVLAD/blob/24474359bc1479845b932a0943fcebd6ef166642/datasets/dataset_data_provider.py#L94), which might need to be updated as per the [new version](https://www.tensorflow.org/versions/master/api_docs/python/tf/reverse).
